# .gitlab-ci.yml
# Author: Robert Van Voorhees <robert_van_voorhees@troweprice.com>
# Description: This is a basic GitLab Runner CI file for building and testing a basic Create React App frontend.
variables:
  CI: 'true'

stages:
  - build
  - test
  - package
  - test-ui
  - sonar
  - deploy

# Run the build first, to make sure that all minification and uglification properly executes.
build:
  image: node:8
  stage: build
  script:
    - npm install
    - CI='' npm run build # CI variable is blanked out due to stupid dependency WARNING that CRA treats as an error in CI
  cache:
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules
  artifacts:
    name: '$CI_COMMIT_REF_NAME'
    paths:
      - build/

test:
  image: node:8
  stage: test
  script:
    - npm install
    - npm run test -- --ci --coverage --reporters=default --reporters=jest-junit
  cache:
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules
  artifacts:
    reports:
      junit: junit.xml

package:
  image: docker:latest
  stage: package
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - ls -la
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  dependencies:
    - build

test-ui:
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
  image:
    name: docker/compose:1.22.0
    entrypoint: ['/bin/sh', '-c']
  stage: test-ui
  cache:
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules
  services:
    - docker:dind
  artifacts:
    reports:
      junit: ./shared/testOutput/e2e-junit.xml
  dependencies:
    - package
  # before_script:
  #   - apk --no-cache add python python-dev py-pip build-base curl bash git
  #   - curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
  #   - chmod +x /usr/local/bin/docker-compose
  #   - pip install docker-compose
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - 'export SHARED_PATH="$(dirname ${CI_PROJECT_DIR})/shared"'
    # This is a little hack since you can't mount the exact folder that is already mounted, so you go one deeper.
    - mkdir -p ${SHARED_PATH} && cp -R . ${SHARED_PATH} && cd ${SHARED_PATH}
    - docker-compose up --timeout 1 --no-build -d
    - docker-compose run tests ./scripts/start-e2e.sh
